//! Who published the registry index, as opposed to whether it arrived intact.
//!
//! Every manifest this app installs is checked against a `sha256` — and that
//! `sha256` comes out of the same `index.toml` as the link to the manifest,
//! fetched from the same host. It proves the bytes were not altered between
//! that host and here. It proves nothing at all about the host: anyone able
//! to serve a different `index.toml` serves matching hashes with it, and the
//! only thing left standing between that and an installed plugin is a trust
//! dialog a person can click through.
//!
//! A signature moves the question from the transport to the publisher. Once
//! a key is pinned (see [`REGISTRY_PUBLIC_KEY`]), the index is signed with an
//! ed25519 key whose public half is compiled into this binary, and the
//! signature is checked *before the index is parsed* — so an index this app
//! will not vouch for is never even read for what it claims about itself.
//! Today `REGISTRY_PUBLIC_KEY` is `None`, so no key is pinned yet: the check
//! still runs, but it answers [`Verification::Unverifiable`] rather than
//! refusing anything, and every index still gets parsed — see that variant's
//! own doc, and `SECURITY.md`'s "Known gaps" section for the same fact
//! stated for a reader who is not this source file.
//!
//! ## Format
//!
//! [minisign](https://jedisct1.github.io/minisign/)'s, so the publisher signs
//! with a tool that exists rather than one this project would have to write:
//!
//! ```text
//! untrusted comment: <anything>
//! <base64: "Ed" | key id (8 bytes) | signature (64 bytes)>
//! trusted comment: <anything>
//! <base64: signature (64 bytes) over the line-2 signature bytes + this comment>
//! ```
//!
//! Both of minisign's algorithms: `Ed`, which signs the file itself, and
//! `ED`, which signs a Blake2b-512 hash of it first. Supporting only the
//! first would have been less code and a trap — which of the two the signing
//! tool produces depends on its version and its flags, and a publisher whose
//! perfectly correct signature is refused by name has no way to tell that
//! from a compromised index. The second signature in the file is verified
//! too, even though nothing here reads either comment: unverified, the
//! trusted comment would be exactly as forgeable as the untrusted one, which
//! makes the distinction between them a lie.
//!
//! The ed25519 itself is `ring`'s. It was already in this binary (rustls
//! reaches it through `ureq`), so the verification this module adds compiles
//! no new cryptographic code at all — which is the same argument the rest of
//! this feature is about.

use base64::Engine;
use blake2::{Blake2b512, Digest};
use ring::signature::{self, UnparsedPublicKey};

/// The public half of the key the registry index is signed with, as the
/// second line of a `minisign.pub` file.
///
/// `None` means this build cannot verify anything, and says so out loud
/// rather than quietly accepting whatever arrives — see [`Verification`].
/// Filling it in is what turns this feature on: from that build onwards an
/// index without a signature this key made is refused outright, so the
/// signature file has to be published alongside `index.toml` first.
///
/// Generated by the publisher with `minisign -G`; the secret half never
/// comes near this repository. Signing is `minisign -Sm index.toml`, with or
/// without `-H` — both forms verify here.
pub const REGISTRY_PUBLIC_KEY: Option<&str> = None;

/// What is known about who published an index.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Verification {
    /// A signature by the pinned key, over exactly these bytes.
    Signed,
    /// No key is pinned in this build, so nothing about the publisher was
    /// established. Deliberately a value the caller has to handle rather than
    /// an `Ok(())` that reads like success: a security check that is off is
    /// only safe while everybody can see that it is off.
    Unverifiable,
}

/// Check `index` against `signature_file` using the key pinned in this build.
///
/// `signature_file` is `None` when the registry serves no `.minisig` at all.
/// With a key pinned that is a refusal, not a shrug — an index nobody signed
/// is an index anyone could have written.
pub fn verify_index(index: &[u8], signature_file: Option<&str>) -> Result<Verification, String> {
    let Some(public_key) = REGISTRY_PUBLIC_KEY else {
        return Ok(Verification::Unverifiable);
    };
    let key = PublicKey::parse(public_key)?;
    let Some(signature_file) = signature_file else {
        return Err(
            "the registry index is not signed, and this build only installs from a \
                    signed index"
                .to_string(),
        );
    };
    let signature = Signature::parse(signature_file)?;
    key.check(index, &signature)?;
    Ok(Verification::Signed)
}

/// A parsed `minisign.pub` second line: algorithm, key id, key.
struct PublicKey {
    id: [u8; 8],
    key: [u8; 32],
}

/// Which of minisign's two signature forms a file carries.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum Algorithm {
    /// `Ed`: signed over the file itself.
    Plain,
    /// `ED`: signed over Blake2b-512 of the file.
    Prehashed,
}

impl PublicKey {
    fn parse(line: &str) -> Result<Self, String> {
        let raw = decode_base64(line.trim(), "public key")?;
        // 2-byte algorithm, 8-byte key id, 32-byte key.
        if raw.len() != 42 {
            return Err(format!(
                "pinned public key is {} bytes, not the 42 a minisign key decodes to — is it the \
                 second line of the `.pub` file?",
                raw.len()
            ));
        }
        // A public key is only ever written `Ed`; the algorithm distinction
        // belongs to the signature, not to the key that made it.
        if &raw[..2] != b"Ed" {
            return Err(format!(
                "pinned public key names algorithm {:?} — a minisign public key is always `Ed`",
                String::from_utf8_lossy(&raw[..2])
            ));
        }
        let mut id = [0u8; 8];
        let mut key = [0u8; 32];
        id.copy_from_slice(&raw[2..10]);
        key.copy_from_slice(&raw[10..]);
        Ok(PublicKey { id, key })
    }

    fn check(&self, index: &[u8], signature: &Signature) -> Result<(), String> {
        if signature.id != self.id {
            // Worth its own message: a signature that is perfectly valid
            // under somebody else's key is the shape a swapped index takes.
            return Err(format!(
                "the index is signed by key {}, not the one this build trusts ({})",
                crate::plugin::hex(&signature.id),
                crate::plugin::hex(&self.id)
            ));
        }
        let key = UnparsedPublicKey::new(&signature::ED25519, self.key);
        // What was actually signed: the file, or its hash. Matched here,
        // at the call, rather than built into an owned `Vec<u8>` first —
        // `index` is already `&[u8]`, so the `Plain` arm has nothing to copy
        // to hand `verify` the reference it wants; only `Prehashed` needs an
        // owned digest to take that reference of.
        let verified = match signature.algorithm {
            Algorithm::Plain => key.verify(index, &signature.signature),
            Algorithm::Prehashed => key.verify(&Blake2b512::digest(index), &signature.signature),
        };
        verified.map_err(|_| "the index does not match its signature".to_string())?;

        // And the trusted comment, which is trusted only because of this.
        let mut signed = signature.signature.to_vec();
        signed.extend_from_slice(signature.trusted_comment.as_bytes());
        key.verify(&signed, &signature.global_signature)
            .map_err(|_| {
                "the signature file's trusted comment does not match its signature".to_string()
            })
    }
}

/// A parsed `.minisig`.
struct Signature {
    algorithm: Algorithm,
    id: [u8; 8],
    signature: [u8; 64],
    trusted_comment: String,
    global_signature: [u8; 64],
}

impl Signature {
    fn parse(text: &str) -> Result<Self, String> {
        let mut lines = text.lines();
        let mut next = |what: &str| -> Result<String, String> {
            lines
                .next()
                .map(str::to_string)
                .ok_or_else(|| format!("signature file ends before its {what}"))
        };
        let _untrusted = next("first comment")?;
        let signature_line = next("signature")?;
        let trusted_line = next("trusted comment")?;
        let global_line = next("second signature")?;

        let raw = decode_base64(signature_line.trim(), "signature")?;
        // 2-byte algorithm, 8-byte key id, 64-byte signature.
        if raw.len() != 74 {
            return Err(format!(
                "signature is {} bytes, not the expected 74",
                raw.len()
            ));
        }
        let algorithm = read_algorithm(&raw[..2])?;

        let trusted_comment = trusted_line
            .strip_prefix("trusted comment: ")
            .ok_or_else(|| {
                "signature file's third line is not a `trusted comment: ` line".to_string()
            })?
            .to_string();

        let global = decode_base64(global_line.trim(), "second signature")?;
        if global.len() != 64 {
            return Err(format!(
                "second signature is {} bytes, not the expected 64",
                global.len()
            ));
        }

        let mut id = [0u8; 8];
        let mut sig = [0u8; 64];
        let mut global_signature = [0u8; 64];
        id.copy_from_slice(&raw[2..10]);
        sig.copy_from_slice(&raw[10..]);
        global_signature.copy_from_slice(&global);
        Ok(Signature {
            algorithm,
            id,
            signature: sig,
            trusted_comment,
            global_signature,
        })
    }
}

/// minisign's two algorithms. Anything else is refused: an unknown tag is a
/// file this build cannot reason about, and guessing at it would be the one
/// place in this module where a wrong guess is silent.
fn read_algorithm(tag: &[u8]) -> Result<Algorithm, String> {
    match tag {
        b"Ed" => Ok(Algorithm::Plain),
        b"ED" => Ok(Algorithm::Prehashed),
        other => Err(format!(
            "unknown signature algorithm {:?} — expected minisign's `Ed` or `ED`",
            String::from_utf8_lossy(other)
        )),
    }
}

fn decode_base64(text: &str, what: &str) -> Result<Vec<u8>, String> {
    base64::engine::general_purpose::STANDARD
        .decode(text)
        .map_err(|e| format!("{what} is not valid base64: {e}"))
}

#[cfg(test)]
mod tests {
    use super::*;
    use ring::signature::{Ed25519KeyPair, KeyPair};

    /// A publisher, for the tests: a key pair plus the ability to produce the
    /// two files minisign would. Signing with the same library that verifies
    /// would be a poor test of the *cryptography* — that is `ring`'s own
    /// business — but this is a test of the file format and the checks around
    /// it, and for those a real signature over real bytes is exactly right.
    struct Publisher {
        pair: Ed25519KeyPair,
        id: [u8; 8],
    }

    impl Publisher {
        fn new(id: u8) -> Self {
            // A fixed seed, so a failure is reproducible.
            let seed = [id; 32];
            let pair = Ed25519KeyPair::from_seed_unchecked(&seed).expect("seed is a key");
            Publisher { pair, id: [id; 8] }
        }

        fn public_line(&self) -> String {
            let mut raw = b"Ed".to_vec();
            raw.extend_from_slice(&self.id);
            raw.extend_from_slice(self.pair.public_key().as_ref());
            base64::engine::general_purpose::STANDARD.encode(raw)
        }

        fn sign(&self, content: &[u8], trusted: &str) -> String {
            self.sign_as(content, trusted, b"Ed")
        }

        /// What minisign writes when it hashes first.
        fn sign_prehashed(&self, content: &[u8], trusted: &str) -> String {
            self.sign_as(&Blake2b512::digest(content), trusted, b"ED")
        }

        fn sign_as(&self, content: &[u8], trusted: &str, algorithm: &[u8; 2]) -> String {
            let signature = self.pair.sign(content);
            let mut line = algorithm.to_vec();
            line.extend_from_slice(&self.id);
            line.extend_from_slice(signature.as_ref());

            let mut global_input = signature.as_ref().to_vec();
            global_input.extend_from_slice(trusted.as_bytes());
            let global = self.pair.sign(&global_input);

            let b64 = |b: &[u8]| base64::engine::general_purpose::STANDARD.encode(b);
            format!(
                "untrusted comment: signature from a test key\n{}\ntrusted comment: {trusted}\n{}\n",
                b64(&line),
                b64(global.as_ref())
            )
        }
    }

    /// [`verify_index`] with the key supplied rather than pinned, so the
    /// tests can exercise a build that has one. The pinned constant is `None`
    /// until the publisher generates a key; every check below is what happens
    /// once it is not.
    fn verify_with(public_key: &str, index: &[u8], sig: Option<&str>) -> Result<(), String> {
        let key = PublicKey::parse(public_key)?;
        let signature = Signature::parse(sig.ok_or("no signature")?)?;
        key.check(index, &signature)
    }

    const INDEX: &[u8] = b"schema_version = 1\n[[plugin]]\nid = \"x\"\n";

    #[test]
    fn a_signature_by_the_pinned_key_over_these_bytes_verifies() {
        let publisher = Publisher::new(7);
        let sig = publisher.sign(INDEX, "timestamp:1787000000\tfile:index.toml");
        assert_eq!(
            verify_with(&publisher.public_line(), INDEX, Some(&sig)),
            Ok(())
        );
    }

    #[test]
    fn one_byte_of_the_index_changing_is_the_whole_point() {
        let publisher = Publisher::new(7);
        let sig = publisher.sign(INDEX, "t");
        let mut tampered = INDEX.to_vec();
        tampered.push(b' ');
        assert_eq!(
            verify_with(&publisher.public_line(), &tampered, Some(&sig)),
            Err("the index does not match its signature".to_string())
        );
    }

    #[test]
    fn a_perfectly_valid_signature_by_the_wrong_key_is_refused() {
        // The shape a swapped index takes: whoever serves it signs it, just
        // not with the key this build trusts.
        let ours = Publisher::new(7);
        let theirs = Publisher::new(9);
        let sig = theirs.sign(INDEX, "t");
        let error = verify_with(&ours.public_line(), INDEX, Some(&sig)).unwrap_err();
        assert!(
            error.contains("not the one this build trusts"),
            "unexpected: {error}"
        );
    }

    #[test]
    fn an_edited_trusted_comment_is_caught_by_the_second_signature() {
        // Which is the only reason that comment is called trusted.
        let publisher = Publisher::new(7);
        let sig = publisher.sign(INDEX, "timestamp:1787000000\tfile:index.toml");
        let edited = sig.replace("file:index.toml", "file:something-else.toml");
        assert_eq!(
            verify_with(&publisher.public_line(), INDEX, Some(&edited)),
            Err("the signature file's trusted comment does not match its signature".to_string())
        );
    }

    #[test]
    fn the_prehashed_form_verifies_too_and_over_the_hash_not_the_file() {
        // Which form the signing tool produces depends on its version and its
        // flags, and a publisher whose correct signature is refused has no way
        // to tell that from a compromised index.
        let publisher = Publisher::new(7);
        let good = publisher.sign_prehashed(INDEX, "t");
        assert_eq!(
            verify_with(&publisher.public_line(), INDEX, Some(&good)),
            Ok(())
        );

        // And it really is over the hash: a signature made the plain way but
        // labelled `ED` is checked against the hash and fails.
        let mislabelled = publisher.sign_as(INDEX, "t", b"ED");
        assert_eq!(
            verify_with(&publisher.public_line(), INDEX, Some(&mislabelled)),
            Err("the index does not match its signature".to_string())
        );
    }

    #[test]
    fn an_algorithm_this_build_does_not_know_is_refused_rather_than_guessed_at() {
        let publisher = Publisher::new(7);
        let sig = publisher.sign_as(INDEX, "t", b"Xx");
        let error = verify_with(&publisher.public_line(), INDEX, Some(&sig)).unwrap_err();
        assert!(
            error.contains("unknown signature algorithm"),
            "unexpected: {error}"
        );
    }

    #[test]
    fn a_signature_file_that_is_not_one_is_refused_rather_than_indexed_into() {
        // It arrives over the network from a host this whole feature exists
        // because it does not trust.
        let publisher = Publisher::new(7);
        let key = publisher.public_line();
        for (what, text) in [
            ("empty", ""),
            ("one line", "untrusted comment: x"),
            (
                "three lines",
                "untrusted comment: x\nAAAA\ntrusted comment: y",
            ),
            (
                "not base64",
                "untrusted comment: x\n!!!!\ntrusted comment: y\nAAAA",
            ),
            (
                "short signature",
                "untrusted comment: x\nRWQ=\ntrusted comment: y\nAAAA",
            ),
            (
                "third line is not a trusted comment",
                &publisher
                    .sign(INDEX, "t")
                    .replace("trusted comment: ", "sneaky comment: "),
            ),
        ] {
            let outcome = verify_with(&key, INDEX, Some(text));
            assert!(outcome.is_err(), "`{what}` must be refused, not parsed");
        }
    }

    #[test]
    fn a_public_key_that_is_not_one_is_refused_before_anything_is_checked() {
        for (what, line) in [
            ("empty", ""),
            ("not base64", "!!!!"),
            ("too short", "RWQ="),
            // The whole `.pub` file pasted in, comment line and all.
            (
                "the file rather than the line",
                "untrusted comment: minisign public key\nRWQ=",
            ),
        ] {
            assert!(
                PublicKey::parse(line).is_err(),
                "`{what}` must not parse as a key"
            );
        }
    }

    #[test]
    fn a_build_with_no_key_pinned_says_so_instead_of_saying_yes() {
        // The state this ships in until the publisher generates a key. It
        // must not be spelled the same way as a successful verification, or
        // the difference between "checked" and "not checked" lives only in a
        // comment.
        assert_eq!(
            REGISTRY_PUBLIC_KEY, None,
            "when this is filled in, the assertions below change"
        );
        assert_eq!(verify_index(INDEX, None), Ok(Verification::Unverifiable));
        assert_ne!(
            verify_index(INDEX, None),
            Ok(Verification::Signed),
            "an unverifiable index must never read as a signed one"
        );
    }
}
